# Apply Token Replacement to Transaction Descriptions

This notebook demonstrates how to apply the finalized `replace_tokens()` function from `preprocess.py` to transform transaction descriptions into a more general, model-friendly format.

In [10]:
import sys
import os
import pandas as pd

sys.path.append(os.path.abspath('..'))

from src.preprocess import replace_tokens

df = pd.read_csv("../data/transactions.csv")
df[['description', 'label']].sample(20, random_state=42)

,description,label
298,Card Purchase Insufficient Funds Fee,Insufficient Funds Fee
39,POS Purchase Nice On 4th * 17 Nov,Eating Out
335,Yoco*recharge Braai Lo Johannesburg (Card ),Fast Food & Takeouts
398,Live Better Interest Sweep,Savings Transfer
153,POS Purchase Crazy Store O4 * 21 Oct,General Purchases
195,POS Purchase KFC Colefax Nkandla * 03 Oct,Eating Out
168,Magtape Debit Bsure CC L Bsure Rf1Lhhvd,Debit Order
101,POS Purchase Superspar Melmoth * 03 Oct,Groceries
397,POS Purchase Mcdonald S Craigh * 27 Oct,Eating Out
30,Interest Received,Interest Received
72,POS Purchase Sasol Broederstroom * 11 Nov,General Purchases
271,International Processing Fee for Insufficient ...,Insufficient Funds Fee
140,POS Purchase Dashpay*Ccm Facilit * 12 Oct,General Purchases
349,Till Cash Withdrawal Fee,Bank Charges and Fees
362,POS Purchase Https://Switchplayg * 25 Oct,Electronics and Appliances
55,Cash Withdrawal Atm Benoni Ns A Benoni Gtza,ATM and Cash Withdrawal
165,POS Purchase Marble Pantry - Arc * 22 Aug,Eating Out
320,Debit Order Dispute Fee,Bank Charges and Fees
287,POS Purchase Parkhurst Mini Mart * 05 Sep,General Purchases
82,POS Purchase The Banchan * 11 Nov,Eating Out

###  Applying the Tokenizer

In [11]:
df['description'] = df.apply(lambda row: replace_tokens(row['description'], row['label']), axis=1)
df[['description', 'label']].sample(20, random_state=42)

,description,label
298,card purchase insufficient funds fee,Insufficient Funds Fee
39,pos purchase [restaurant] [date],Eating Out
335,yoco*recharge braai lo johannesburg (card ),Fast Food & Takeouts
398,live better interest sweep,Savings Transfer
153,pos purchase crazy store o4 [date],General Purchases
195,pos purchase [restaurant] [location] [date],Eating Out
168,magtape debit bsure cc l bsure rf1lhhvd,Debit Order
101,pos purchase [grocers] melmoth [date],Groceries
397,pos purchase [restaurant] [date],Eating Out
30,interest received,Interest Received
72,pos purchase [garage] broederstroom [date],General Purchases
271,international processing fee for insufficient ...,Insufficient Funds Fee
140,pos purchase dashpay*ccm facilit [date],General Purchases
349,till cash withdrawal fee,Bank Charges and Fees
362,pos purchase https://switchplayg [date],Electronics and Appliances
55,cash withdrawal atm benoni ns a benoni gtza,ATM and Cash Withdrawal
165,pos purchase [restaurant] [location] [date],Eating Out
320,debit order dispute fee,Bank Charges and Fees
287,pos purchase parkhurst mini mart [date],General Purchases
82,pos purchase [restaurant] [date],Eating Out

In [13]:
df.to_csv('../data/transactions_tokenized.csv', index=False)